{{- if .Values.config.migration.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "core.postgres.job.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
  {{- with merge .Values.config.migration.serviceAccount.annotations (include "core.postgres.job.sa.annotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
