global:
  aws:
    elb: true

membership:
  ingress:
    enabled: false
  aws:
    targetGroups:
      http:
        targetGroupARN: ""
      grpc: # H2C
        targetGroupARN: ""
  dex:
    ingress:
      enabled: false
    aws:
      targetGroups:
        dex-http:
          targetGroupARN: ""

portal:
  ingress:
    enabled: false
  aws:
    targetGroups:
      http:
        targetGroupARN: ""
