{{ if and .Values.versions.create }}
{{- range $key, $version := .Values.versions.files }}
apiVersion: formance.com/v1beta1
kind: Versions
metadata:
  name: {{ $key }}
  {{- if or (eq $key "default") (gt (semver $key | (semver "v2.0.0").Compare) 0) }}
  annotations:
    formance.com/deprecated: "true"
  {{- end }}
spec:
  {{- range $k, $v := $version }}
  {{ $k }}: {{ $v }}
  {{- end }}
---
{{- end }}
{{- end }}
