{{- $allowDefaultVersion := .Values.versions.allowDefaultVersion | default false -}}
{{ if and .Values.versions.create }}
{{- range $key, $version := .Values.versions.files }}
apiVersion: formance.com/v1beta1
kind: Versions
metadata:
  name: {{ $key }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- if eq $key "default" }}
    {{- if not $allowDefaultVersion }}
    formance.com/deprecated: "true"
    {{- end }}
    {{- else }}
    {{- if gt (semver $key | (semver "v2.0.0").Compare) 0 }}
    formance.com/deprecated: "true"
    {{- end }}
    {{- end }}
spec:
  {{- range $k, $v := $version }}
  {{ $k }}: {{ $v }}
  {{- end }}
---
{{- end }}
{{- end }}
